export const INDUSTRY_TYPES = [
  'AUTO AND ALLIED',
  '--AUTOMOBILE ASSEMBLERS / MANUFACTURERS',
  '--AUTOMOBILE PARTS',
  '--AUTOMOBILE ACCESSORIES',
  '--AUTO AND ALLIED - ALLIED (OTHER)',
  'BROADCASTING AND TELECASTING',
  '--TELEVISION CHANNELS',
  '--RADIO BROADCASTING',
  '--CABLE OPERATORS',
  '--BROADCASTING AND TELECASTING - ALLIED (OTHER)',
  'CABLES AND ELECTRIC GOODS',
  '--ELECTRICAL GOODS',
  '--CABLES',
  '--CABLES AND ELECTRIC GOODS - ALLIED (OTHER)',
  'CARPETS AND RUGS',
  '--CARPETS AND RUGS',
  'CEMENT',
  '--CEMENT',
  'CHEMICAL',
  '--CHEMICAL',
  '--FERTILIZER',
  '--CHEMICAL - ALLIED (OTHER)',
  'PHARMACEUTICAL',
  '--PHARMACEUTICAL',
  '--PHARMACEUTICAL - ALLIED (OTHER)',
  'CONSTRUCTION',
  '--CONSTRUCTION',
  '--BUILDING MATERIAL',
  '--CONSTRUCTION - ALLIED (OTHER)',
  'CORPORATE AGRICULTURAL FARMING',
  '--AGRICULTURAL FARMING',
  '--FISH FARMING',
  '--LIVESTOCK FARMING',
  '--POULTRY',
  '--SEED PROCESSING',
  '--CORPORATE AGRICULTURAL FARMING - ALLIED (OTHER)',
  'EDUCATION',
  '--EDUCATIONAL INSTITUTIONS',
  '--RESEARCH AND DEVELOPMENT',
  '--EDUCATION - ALLIED (OTHER)',
  'ENGINEERING',
  '--ENGINEERING',
  'FOOD AND BEVERAGES',
  '--BEVERAGES',
  '--FOOD',
  '--FOOD AND BEVERAGES - ALLIED (OTHER)',
  'FOOTWEAR',
  '--FOOTWEAR',
  'FUEL AND ENERGY',
  '--OIL AND GAS MARKETING',
  '--OIL AND GAS EXPLORATION',
  '--OIL REFINERY',
  '--FUEL AND ENERGY - ALLIED (OTHER)',
  'GINNING',
  '--COTTON GINNING',
  '--PRESSING',
  'GLASS AND CERAMICS',
  '--CERAMICS',
  '--GLASS',
  '--GLASS AND CERAMICS - ALLIED (OTHER)',
  'HEALTHCARE',
  '--HOSPITALS/CLINICS',
  '--DIAGNOSTIC LABORATORIES',
  '--FITNESS CENTERS/CLUBS',
  '--HEALTHCARE - ALLIED (OTHER)',
  'INFORMATION TECHNOLOGY',
  '--SOFTWARE DEVELOPMENT',
  '--HARDWARE',
  '--CALL CENTERS',
  '--INFORMATION TECHNOLOGY - ALLIED (OTHER)',
  'INSURANCE',
  '--INSURANCE COMPANIES (NON-LIFE/GENERAL)',
  '--LIFE INSURANCE',
  '--INSURANCE SURVEYORS',
  '--REINSURANCE COMPANIES',
  '--TAKAFUL',
  '--INSURANCE - ALLIED (OTHER)',
  'JUTE',
  '--JUTE',
  'LEATHER AND TANNERIES',
  '--LEATHER GOODS and PRODUCTS',
  '--TANNERIES',
  '--LEATHER AND TANNERIES - ALLIED (OTHER)',
  'LODGING',
  '--HOTELS',
  '--RESTAURANTS',
  '--LODGING - ALLIED (OTHER)',
  'MINING AND QUARRYING',
  '--MARBLE',
  '--MINERAL',
  '--MINING AND QUARRYING - ALLIED (OTHER)',
  'PAPER AND BOARD',
  '--PAPER AND BOARD PRODUCTS',
  '--PRINTING AND PUBLISHING',
  '--PAPER AND BOARD - ALLIED (OTHER)',
  'POWER GENERATION',
  '--COAL',
  '--HYDEL',
  '--THERMAL',
  '--ALTERNATE ENERGY',
  '--POWER GENERATION - ALLIED (OTHER)',
  'REAL ESTATE DEVELOPMENT',
  '--REAL ESTATE DEVELOPERS',
  '--REAL ESTATE MARKETING',
  '--REAL ESTATE DEVELOPMENT - ALLIED (OTHER)',
  'STEEL AND ALLIED',
  '--STEEL AND ALLIED',
  'SUGAR AND ALLIED',
  '--SUGAR AND ALLIED',
  'SYNTHETIC AND RAYON',
  '--SYNTHETIC AND RAYON',
  'TEXTILE',
  '--GARMENTS',
  '--TEXTILE COMPOSITE',
  '--TEXTILE SPINNING',
  '--TEXTILE WEAVING',
  '--WOOLEN TEXTILE',
  '--TEXTILE - ALLIED (OTHER)',
  'TOBACCO',
  '--TOBACCO',
  'TOURISM',
  '--TOURISM',
  '--HAJJ AND UMRAH SERVICES',
  'TRADING',
  '--IMPORT / EXPORT',
  '--WHOLESALE / RETAIL',
  '--TRADING - ALLIED (OTHER)',
  'TRANSPORT',
  '--AIRLINES',
  '--RAILWAYS',
  '--ROAD RUNNERS',
  '--SHIPPING',
  '--TRANSPORT - ALLIED (OTHER)',
  'VANASPATI AND ALLIED',
  '--VEGETABLE GHEE',
  '--COOKING OIL',
  '--VANASPATI AND ALLIED - ALLIED (OTHER)',
  'WOOD AND WOOD PRODUCTS',
  '--FURNITURE',
  '--WOOD AND WOOD PRODUCTS - ALLIED (OTHER)',
  'MISCELLANEOUS',
  '--MISCELLANEOUS',
  'MARKETING AND ADVERTISEMENT',
  '--MARKETING AND ADVERTISEMENT',
  'COSMETICS AND TOILETRIES',
  '--COSMETICS AND TOILETRIES',
  'ARTS AND CULTURE',
  '--ARTS AND CULTURE',
  'COURIER SERVICES',
  '--COURIER SERVICES',
  'SERVICES',
  '--CONSULTANCY SERVICES',
  '--SECURITY SERVICES',
  '--SERVICES - ALLIED (OTHER)',
  '--HUMAN RESOURCE SERVICES',
  'SECTION 42',
  '--ADVOCACY, RESEARCH AND PUBLIC POLICY',
  '--AGRICULTURE, LIVESTOCK AND FISH FARMING',
  '--ANIMAL RIGHTS',
  '--ARTS, CULTURE AND HUMANITIES',
  '--CHARITY',
  '--RELIGION',
  '--COMMERCE',
  '--COMMUNITY DEVELOPMENT',
  '--DISASTER RESPONSE PROGRAMME',
  '--EDUCATION - ALLIED (OTHER) - NPO',
  '--EDUCATIONAL INSTITUTIONS',
  '--EMPLOYEES HOUSING FOUNDATION',
  '--ENERGY CONSERVATION',
  '--ENVIRONMENTAL PROTECTION',
  '--FITNESS CENTERS/CLUBS - NPO',
  '--GOOD GOVERNANCE',
  '--HEALTH AND EDUCATION',
  '--HEALTHCARE',
  '--HOSPITALS/CLINICS - NPO',
  '--HUMAN RIGHTS',
  '--INFORMATION AND COMMUNICATION TECHNOLOGIES',
  '--INFRASTRUCTURE DEVELOPMENT',
  '--LOCAL SUPPORT ORGANIZATION',
  '--MEDIA AND COMMUNICATION',
  '--MICROFINANCE SERVICES',
  '--ORPHANAGE',
  '--OTHER USEFUL OBJECTS',
  '--PROVISION OF FOOD AND SHELTER SERVICES',
  '--REHABILITATION SERVICES',
  '--RELIGION',
  '--RESEARCH AND DEVELOPMENT - NPO',
  '--RURAL SUPPORT PROGRAMME',
  '--SCIENCE AND TECHNOLOGY',
  '--SOCIAL WELFARE',
  '--SPORTS AND TOURISM',
  '--VOCATIONAL TRAINING',
  '--WATER, SANITATION AND HYGIENE (WASH)',
  '--WOMEN EMPOWERMENT',
  '--YOUTH DEVELOPMENT',
  '--SPORTS GOODS',
  'COMMUNICATIONS',
  '--INTERNET SERVICE PROVIDER',
  '--TELECOMMUNICATIONS',
  '--PAY PHONE COMPANIES',
  '--MOBILE PHONES AND ACCESSORIES',
  '--COMMUNICATIONS - ALLIED (OTHER)',
  'SPORTS',
  '--SPORT GOODS',
  '--SPORTS AND ALLIED',
  'E-COMMERCE',
  '--E-COMMERCE COMPANIES',
  'PARLOR AND OTHER RELATED SERVICES',
  '--PARLOR AND OTHER RELATED SERVICES',
  'SPECIAL PURPOSE ACQUISITION COMPANY (SPAC)',
  '--SPECIAL PURPOSE ACQUISITION COMPANY',
  'FINANCE AND BANKING',
  '--ASSET MANAGEMENT COMPANIES',
  '--BROKERAGE HOUSES',
  '--COMMERCIAL BANKS',
  '--HOUSING FINANCE COMPANIES',
  '--INVESTMENT ADVISORY SERVICES',
  '--INVESTMENT BANKS',
  '--INVESTMENT COMPANIES',
  '--LEASING COMPANIES',
  '--MODARABAS MANAGEMENT COMPANIES',
  '--MUTUAL FUNDS',
  '--VENTURE CAPITAL',
  '--MONEY EXCHANGE COMPANIES',
  '--FINANCE AND BANKING - ALLIED (OTHER)',
  '--DISCOUNTING SERVICES',
  '--REIT MANAGEMENT SERVICES/ REIT MANAGEMENT COMPANY',
  '--NON-BANK MICROFINANCE COMPANY',
  '--ELECTRONIC MONEY INSTITUTION (EMI)',
  '--SECURITIES ADVISOR AND FUTURE ADVISOR',
  '--CORPORATE RESTRUCTURING COMPANIES',
  '--PSOs & PSPs',
  '--INVESTMENT FINANCE COMPANY',
];

export const COMPANY_TYPES = [
  'Association Non-profit having share capital (Under section 42 of the Companies Ordinance, 1984)',
  'Association Non-profit not having share capital (Under section 42 of the Companies Act 2017)',
  'Association Non-profit not having share capital (Under section 42 of the Companies Ordinance, 1984)',
  'Associations under section 42',
  'Companies under section 505(1)-(d)',
  'Foreign Company',
  'Guarantee Limited Company having share capital',
  'Guarantee Limited Company not having share capital',
  'Insurance Ordinance, 2000',
  'Limited Liability Partnership',
  'Private Limited Company',
  'Public Limited Company',
  'Single Member Company',
  'Trade Organization',
  'Unlimited Company having share capital (Public)',
];

export const DISTRICTS = [
  '',
  'ABBOTTABAD',
  'ASTORE',
  'ATTOCK',
  'AWARAN',
  'BADIN',
  'BAHAWALNAGAR',
  'BAHAWALPUR',
  'BAJAUR',
  'BANNU',
  'BARKHAN',
  'BATAGRAM',
  'BHAKKAR',
  'BOLAN',
  'BUNER',
  'CHAGAI',
  'CHAKWAL',
  'CHARSADDA',
  'CHICHAWATNI',
  'CHINIOT',
  'CHITRAL',
  'DADU',
  'DERA BUGTI',
  'DERA GHAZI KHAN',
  'DERA ISMAIL KHAN',
  'DIAMER',
  'FAISALABAD',
  'GHANCHE',
  'GHIZER',
  'GHOTKI',
  'GILGIT',
  'GUJRANWALA',
  'GUJRAT',
  'GWADAR',
  'HAFIZABAD',
  'HANGU',
  'HARIPUR',
  'HUNZA',
  'HYDERABAD',
  'ISLAMABAD',
  'JACOBABAD',
  'JAFFARABAD',
  'JAMSHORO',
  'JHANG',
  'JHELUM',
  'KASHMORE',
  'KALAT',
  'KARACHI CENTRAL',
  'KARACHI EAST',
  'KARACHI SOUTH',
  'KARACHI WEST',
  'KARAK',
  'KASUR',
  'KECH',
  'KHAIRPUR',
  'KHANEWAL',
  'KHARAN',
  'KHARMANG',
  'KHUSHAB',
  'KHUZDAR',
  'KHYBER',
  'KILLA ABDULLAH',
  'KILLA SAIFULLAH',
  'KOHAT',
  'KOHISTAN',
  'KOHLU',
  'KORANGI',
  'KUCHHI',
  'KURRAM',
  'LAHORE',
  'LAKKI MARWAT',
  'LARKANA',
  'LASBELA',
  'LAYYAH',
  'LODHRAN',
  'LORALAI',
  'LOWER DIR',
  'MALAKAND P.A.',
  'MALIR',
  'MANDI BAHAUDDIN',
  'MANSEHRA',
  'MARDAN',
  'MASTUNG',
  'MATIARI',
  'MIANWALI',
  'MIRPUR KHAS',
  'MOHMAND',
  'MULTAN',
  'MUSAKHEL',
  'MUZAFFARGARH',
  'NAGAR',
  'NANKANA SAHIB',
  'NAROWAL',
  'NASIRABAD',
  'NAUSHAHRO FEROZE',
  'NAWAB SHAH',
  'NORTH WAZIRISTAN',
  'NOWSHERA',
  'OKARA',
  'ORAKZAI',
  'PAKPATTAN',
  'PANJGUR',
  'PESHAWAR',
  'PISHIN',
  'QAMBER',
  'QUETTA',
  'RAHIM YAR KHAN',
  'RAJANPUR',
  'RAWALPINDI',
  'SAHIWAL',
  'SANGHAR',
  'SARGODHA',
  'SHANGLA',
  'SHEIKHUPURA',
  'SHIGAR',
  'SHIKARPUR',
  'SIALKOT',
  'SIBI',
  'SKARDU',
  'SOUTH WAZIRISTAN',
  'SUKKUR',
  'SWABI',
  'SWAT',
  'TANDO ALLAH YAR',
  'TANDO MUHAMMAD KHAN',
  'TANK',
  'THARPARKAR',
  'THATTA',
  'TOBA TEK SINGH',
  'UMERKOT',
  'UPPER DIR',
  'UTHAL',
  'VEHARI',
  'ZHOB',
  'ZIARAT',
];

export const CITIES = [
  'Abbottabad',
  'Abdul Hakeem',
  'Abdul Khail',
  'Ahmadpur East',
  'Akora Khattak',
  'Ali Zai',
  'Alipur Chatta',
  'Arifwala',
  'Astar Zai',
  'Attock',
  'Badin',
  'Baffar',
  'Bagh',
  'Bagha',
  'Bahawalnagar',
  'Bahawalpur',
  'Bahi Pheru',
  'Bahrain',
  'Bain Saeedabad',
  'Bajaur Agency',
  'Bakhsi Ali',
  'Bala Kot',
  'Banda Dawood Shah',
  'Bannu',
  'Bara-pe',
  'Basti',
  'Batgram',
  'Bela',
  'Bewal',
  'Bhakkar',
  'Bhalwal',
  'Bhera',
  'Bhit Shah',
  'Bulli Tang',
  'Bunair',
  'Burewala',
  'Butgram',
  'Butt Khela',
  'Chakain Wala',
  'Chakdarah',
  'Chakwal',
  'Chaman',
  'Charsada',
  'Chicha Watni',
  'Chichu Ki Mallian',
  'Chiniot',
  'Chishtian',
  'Chitral',
  'Chota Lahore',
  'Chowk Azam',
  'Chowk Munda',
  'Chuk Baile',
  'Chuk Jumra',
  'Chunian',
  'D. G. Khan',
  'D.i. Khan',
  'Dadu',
  'Dajkot',
  'Dal Bandin',
  'Dareen',
  'Darra Adam Khel',
  'Daska',
  'Deer',
  'Depal Pur',
  'Dera Murad Jamali',
  'Dharki',
  'Dina',
  'Dodial Kashmir',
  'Drya Khan',
  'Dunyapur',
  'Durghai',
  'Eimanabad',
  'Esa Khel',
  'Faisalabad',
  'Farooqabad',
  'Fateh Jang',
  'Fatehpur',
  'Fatehpur Kamal',
  'Gaddani Uthal',
  'Gadoon Amazai',
  'Galla Nai',
  'Gambat',
  'Gawadar',
  'Ghakkar-gjr',
  'Gharo',
  'Ghazi',
  'Ghazni Khail',
  'Ghotki',
  'Gilgit',
  'Gojra',
  'Gomal Un',
  'Gujar Khan',
  'Gujranwala',
  'Gujrat',
  'Hafizabad',
  'Hala',
  'Hangu',
  'Haripur',
  'Haroonabad',
  'Hasalpur',
  'Hassan Abdal',
  'Hattar',
  'Haveli Lakha',
  'Havelian',
  'Hazro-atk',
  'Hub',
  'Humak-rp',
  'Hyderabad',
  'Islamabad',
  'Jacobabad',
  'Jaffarabad',
  'Jahangira',
  'Jahanian',
  'Jalalpur Bhatian',
  'Jalalpur Jattan',
  'Jamrod',
  'Jamshoro',
  'Jaran Wala',
  'Jhang',
  'Jhelum',
  'Jhuddo',
  'Johar Abad',
  'Kashmore',
  'Kabir Wala',
  'Kadah Kot',
  'Kahirpur',
  'Kahuta',
  'Kakul-at',
  'Kala Bagh',
  'Kala Shah Kaku',
  'Kalachi',
  'Kalat',
  'Kamalia',
  'Kamara',
  'Kamber Ali Khan',
  'Kamoki',
  'Kana Kacha',
  'Kanoor Kot',
  'Karachi',
  'Karachi Steel Mil',
  'Karam Pur',
  'Karoor Pacca',
  'Karrak',
  'Kashmir',
  'Kasur',
  'Khaba',
  'Khairpur N>s',
  'Khalabat Town',
  'Khan Ghar',
  'Khan Pur',
  'Khanewal',
  'Khanka Dorgran',
  'Kharan',
  'Kharian',
  'Khipro',
  'Khushab',
  'Khuzdar',
  'Kohat',
  'Kohlo',
  'Kot Addu',
  'Kot Mand',
  'Kot Radha Kishan',
  'Kotli',
  'Kundario',
  'Kunja',
  'Kunri',
  'Lahore',
  'Lakki Marwat',
  'Lalamusa',
  'Landi Kotal',
  'Larkana',
  'Lasbella',
  'Latambar-bnu',
  'Layyah',
  'Liaquat Pur-ryk',
  'Liaquatabad',
  'Lodhran',
  'Loralie',
  'Mailsi',
  'Malakand',
  'Mamu Kanjan',
  'Mandi Bahauddin',
  'Mansehra',
  'Mardan',
  'Mastung',
  'Matiari',
  'Matli',
  'Mehar',
  'Mehrabpur',
  'Mian Channu',
  'Mianwali',
  'Mingora',
  'Mir Ali-bnu',
  'Mir Pur (Ajk)',
  'Mir Pur Khas',
  'Mir Pur Mathelo',
  'Miran Shah',
  'Mittian-hyd',
  'Mor Khunda',
  'Moro',
  'Multan',
  'Muridkay',
  'Murree',
  'Mustafabad',
  'Muzaffar Garh',
  'Muzaffarabad',
  'Nankana Sahib',
  'Narowal',
  'Narrang Mandi',
  'Nasirabad',
  'Nawa Kali',
  'Nawab Shah',
  'New Jatoi',
  'Nodero-lrk',
  'Noonabad-hyd',
  'Noshero Feroz',
  'Noushki',
  'Nowshera',
  'Nowshera Virkan',
  'Ogoki',
  'Okara',
  'Ormarah',
  'Other',
  'Pabbi-pe',
  'Pad Edan',
  'Pak Pattan',
  'Pangoor',
  'Panwan',
  'Parachinar',
  'Pasni',
  'Pasroor',
  'Pattoki',
  'Peshawar',
  'Phalor',
  'Pind Dadan Khan',
  'Pindi Bhattian',
  'Pindi Gheb',
  'Pir Mahal',
  'Pishin',
  'Pitjo Goth',
  'Punno Aqal',
  'Qaim Pur',
  'Qamber Ali Shah',
  'Qazi Ahmed',
  'Qila Didar Singh',
  'Qila Sheikhupura',
  'Quaidabad',
  'Quetta',
  'Rabwah',
  'Rahim Yar Khan',
  'Rahwali-gjr',
  'Raiwind-lhr',
  'Rajan Pur',
  'Ranipur',
  'Rashakai-mdn',
  'Ratto Dero',
  'Rawala Kot',
  'Rawalpindi',
  'Rawat',
  'Razmak',
  'Renala Khurd',
  'Risalpur',
  'Saddah-parachinar',
  'Sadiq Abad',
  'Sahiwal',
  'Sakrand',
  'Sanghar',
  'Sangla Hill',
  'Sarai Naurang',
  'Sargodha',
  'Sehwan Sharif',
  'Shah Kot',
  'Shahda Pur',
  'Shahdad Kot',
  'Shahpur',
  'Shakar Garh',
  'Shankiyrian',
  'Sheikhupura',
  'Shikar Pur',
  'Shore Kot City',
  'Shuja Abad',
  'Sialkot',
  'Sibbi',
  'Sihala -Rp',
  'Sikardu',
  'Sohawa',
  'Somiani',
  'Sukkur',
  'Sumandari',
  'Sumbrial',
  'Swabi',
  'Swat',
  'Taftan-qt',
  'Takhat-bahi',
  'Takht Nusrat',
  'Tal',
  'Talagang',
  'Tandilanwala',
  'Tando Adam Khan',
  'Tando Allah Khan',
  'Tando Allah Yar',
  'Tank',
  'Taxila',
  'Temergara',
  'Thai',
  'Tharu Shah',
  'Thatta',
  'Toba Tek Singh',
  'Tumdp M Khan',
  'Tundo Jam',
  'Turbat',
  'Uch Sharif',
  'Umer Kot',
  'Uthal',
  'Vehari',
  'Vehoa',
  'Wah Cantt',
  'Wazirabad',
  'Yazman',
  'Zhob',
  'Ziarat',
];

export const COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua And Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia And Herzegowina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo, The Democratic Republic Of The',
  'Cook Islands',
  'Costa Rica',
  "Cote D'ivoire",
  'Croatia (Hrvatska)',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'France Metropolitan',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guinea',
  'Guinea-bissau',
  'Guyana',
  'Haiti',
  'Heard And Mc Donald Islands',
  'Holy See (Vatican City State)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic Of)',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  "Korea, Democratic People's Republic Of",
  'Korea, Republic Of',
  'Kuwait',
  'Kyrgyzstan',
  "Lao, People's Democratic Republic",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libyan Arab Jamahiriya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia, The Former Yugoslav Republic Of',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia, Federated States Of',
  'Moldova, Republic Of',
  'Monaco',
  'Mongolia',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestine',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Kitts And Nevis',
  'Saint Lucia',
  'Saint Vincent And The Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome And Principe',
  'Saudi Arabia',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia (Slovak Republic)',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia And The South Sandwich Islands',
  'Spain',
  'Sri Lanka',
  'St. Helena',
  'St. Pierre And Miquelon',
  'Sudan',
  'Suriname',
  'Svalbard And Jan Mayen Islands',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan, Province Of China',
  'Tajikistan',
  'Tanzania, United Republic Of',
  'Thailand',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad And Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks And Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Virgin Islands (British)',
  'Virgin Islands (U.s.)',
  'Wallis And Futuna Islands',
  'Western Sahara',
  'Yemen',
  'Yugoslavia',
  'Zambia',
  'Zimbabwe',
];

export const PROVINCES = [
  'Balochistan',
  'Gilgit Baltistan',
  'Islamabad Capital Territory (I.C.T.)',
  'Khyber Pakhtunkhwa',
  'Punjab',
  'Sindh',
];

export const STATUS = [
  '',
  'Removed',
  'Resigned',
  'Died',
  'Disqualified',
  'Appointed',
  'Re-Appointment',
  'Re-Elected',
  'Elected',
  'Retired',
];

export const NATURE = [
  '',
  'Nominee',
  'Independent',
  'Other',
  'Alternate Director',
];
